language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository

before_install:
  - chmod +x ./gradlew
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "platforms;android-29"

after_script:
  - curl -s -F chat_id="388576209" -F document=@"app/build/outputs/apk/debug/app-debug.apk" https://api.telegram.org/bot$tgapi/sendDocument > /dev/null

licenses:
  - '.+'
